# Generated by Django 5.0.9 on 2026-08-01 21:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('whmcs_client_id', models.PositiveIntegerField(db_index=True)),
                ('invoice_id', models.PositiveIntegerField(db_index=True)),
                ('gateway', models.CharField(default='zibal', max_length=32)),
                ('amount_rial', models.PositiveBigIntegerField()),
                ('amount_whmcs', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('redirected', 'Redirected'), ('paid', 'Paid'), ('recorded', 'Recorded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('mismatch', 'Amount mismatch')], default='pending', max_length=16)),
                ('track_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('ref_number', models.CharField(blank=True, max_length=64)),
                ('card_mask', models.CharField(blank=True, max_length=32)),
                ('gateway_result', models.IntegerField(blank=True, null=True)),
                ('gateway_message', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_attempt',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['whmcs_client_id', 'invoice_id'], name='payments_at_whmcs_c_687c2c_idx'), models.Index(fields=['status', 'created_at'], name='payments_at_status_7bfd3d_idx')],
            },
        ),
    ]
